### ISSUE TITLE
String color in Ruby

### ISSUE THREAD

**Issue by GuilhermeMedeiross** [arthurdiegoo/the-great-dreamer-theme#1]
The string color could be more highlighted. In the image below we can see this issue. The color of others markups merge with the string color.

<img width="259" alt="Capturar" src="https://user-images.githubusercontent.com/17435953/89454996-f877df00-d737-11ea-9c35-e0bee9754ef3.PNG">

I just test it in ruby language.

**Comment by arthur404dev** [comment]
Great feedback! Will push ruby coverage to next version!
