### ISSUE TITLE
Status Bar - color bugged  

### ISSUE THREAD

**Issue by qeiynn** [arthurdiegoo/the-great-dreamer-theme#5]
The color of the Status Bar is not the same as the provided screenshots in your plugin's description. Maybe some recent update broke it. It is now difficult to read.

Windows 10, Version 20H2
Visual Sudio Code Version: 1.52.1

![statusbar](https://user-images.githubusercontent.com/67804350/104164139-c578fc00-53f7-11eb-9fba-4e232833b1af.JPG)

**Comment by qeiynn** [comment]
Turns out that opening a folder with VScode with "right click > with Code open" fixed it.

**Comment by qeiynn** [comment]
Update: 
Starting VScode by double clicking directly on a .py file brings back the issue (purple status bar). 
As soon as I open a folder the status bar color changes again to the correct one. 
Is it supposed to be like this?

**Comment by arthur404dev** [comment]
> Update:
> Starting VScode by double clicking directly on a .py file brings back the issue (purple status bar).
> As soon as I open a folder the status bar color changes again to the correct one.
> Is it supposed to be like this?

This code separation was added on the latest vscode iteration, on our next release this month this will be fixed for files without folder opened on vscode.

`"statusBar.noFolderBackground"`
